services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:     
        UID: 1000
        GID: 1000
    container_name: laravel_app
    volumes:
      - ../src:/var/www:z
    working_dir: /var/www
    ports:
      - "8989:80" 
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www:z
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:z
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:17
    container_name: laravel_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mook
      POSTGRES_PASSWORD: mook
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ycode@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mook
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel: 

volumes:
  pgdata: